#include "auth/Registration.hpp"

#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/hmac.h>
#include <openssl/rand.h>

#include <stdexcept>
#include <vector>

#include "auth/crypto_utils.hpp"
#include "auth/server_keys.hpp"

namespace auth {

namespace {

// RSA-OAEP/SHA-256 encryption with the server's public key.
// Used for both E = Enc(PKs, B⊕R) and ED = Enc(PKs, D).
std::vector<uint8_t> EncryptWithServerPubKey(
    const std::vector<uint8_t>& plaintext) {
  EVP_PKEY* pub = internal::GetServerKeys().pub();

  internal::EvpPkeyCtxPtr ctx(EVP_PKEY_CTX_new(pub, nullptr));
  if (!ctx) throw std::runtime_error("EVP_PKEY_CTX_new failed");
  if (EVP_PKEY_encrypt_init(ctx.get()) != 1)
    throw std::runtime_error("EVP_PKEY_encrypt_init failed");
  if (EVP_PKEY_CTX_set_rsa_padding(ctx.get(), RSA_PKCS1_OAEP_PADDING) != 1)
    throw std::runtime_error("set_rsa_padding failed");
  if (EVP_PKEY_CTX_set_rsa_oaep_md(ctx.get(), EVP_sha256()) != 1)
    throw std::runtime_error("set_rsa_oaep_md failed");

  size_t outlen = 0;
  if (EVP_PKEY_encrypt(ctx.get(), nullptr, &outlen, plaintext.data(),
                       plaintext.size()) != 1)
    throw std::runtime_error("EVP_PKEY_encrypt (size query) failed");

  std::vector<uint8_t> ciphertext(outlen);
  if (EVP_PKEY_encrypt(ctx.get(), ciphertext.data(), &outlen, plaintext.data(),
                       plaintext.size()) != 1)
    throw std::runtime_error("EVP_PKEY_encrypt failed");

  ciphertext.resize(outlen);
  return ciphertext;
}

}  // namespace

// Protocol 1 — Registration (4-arg form, updated).
//
// Changes from V1:
//   • server_r (R) is an explicit input parameter: the server generates R
//     and sends it to the user before this function is called.
//   • E is now Enc(PKs, B⊕R) instead of Enc(PKs, B).
//   • The returned RegistrationPayload carries R so the server can store it
//     in T_U = {U, R, E, ED}.
//
// Security rationale: XORing B with the server-supplied nonce R before
// encryption means an attacker who only compromises the user device cannot
// mount an offline attack using just E — they also need R, which never
// leaves the server.
auto RegisterUser(
    const std::string& username, std::vector<uint8_t>& password,
    const std::vector<uint8_t>& server_r,
    std::unordered_map<std::string, std::vector<uint8_t>>& local_db)
    -> RegistrationPayload {
  const size_t kKeySize = 16;   // 128-bit S and B  (N = 128 per paper)
  const size_t kHashSize = 32;  // SHA-256 output

  if (server_r.size() != kKeySize)
    throw std::runtime_error("server_r must be exactly kKeySize bytes");

  // ── Step 1: S, B ←$ {0,1}^128 ─────────────────────────────────────────
  std::vector<uint8_t> salt_s(kKeySize);
  std::vector<uint8_t> secret_b(kKeySize);
  if (RAND_bytes(salt_s.data(), static_cast<int>(salt_s.size())) != 1 ||
      RAND_bytes(secret_b.data(), static_cast<int>(secret_b.size())) != 1)
    throw std::runtime_error("CSPRNG generation failed");

  // ── Step 2: Compute B⊕R ────────────────────────────────────────────────
  // Per updated Protocol 1: the secret encrypted under PKs is B⊕R,
  // not B alone.  R was generated by the server and sent to the user.
  std::vector<uint8_t> b_xor_r(kKeySize);
  internal::XorBytes(secret_b, server_r, b_xor_r);

  // ── Step 3: E ← Enc(PKs, B⊕R) ─────────────────────────────────────────
  const std::vector<uint8_t> encrypted_b_xor_r =
      EncryptWithServerPubKey(b_xor_r);
  OPENSSL_cleanse(b_xor_r.data(), b_xor_r.size());  // wipe intermediate

  // ── Step 4: C ← H(S, P) ────────────────────────────────────────────────
  internal::EvpMdCtxPtr mdctx(EVP_MD_CTX_new());
  if (!mdctx) throw std::runtime_error("Failed to create EVP_MD_CTX");

  std::vector<uint8_t> hash_c(kHashSize);
  unsigned int hash_len = 0;
  if (EVP_DigestInit_ex(mdctx.get(), EVP_sha256(), nullptr) != 1 ||
      EVP_DigestUpdate(mdctx.get(), salt_s.data(),
                       static_cast<int>(salt_s.size())) != 1 ||
      EVP_DigestUpdate(mdctx.get(), password.data(),
                       static_cast<int>(password.size())) != 1 ||
      EVP_DigestFinal_ex(mdctx.get(), hash_c.data(), &hash_len) != 1)
    throw std::runtime_error("SHA-256 computation failed");

  // ── Step 5: D ← HMAC_B(C) ──────────────────────────────────────────────
  std::vector<uint8_t> verifier_d(kHashSize);
  unsigned int hmac_len = 0;
  if (HMAC(EVP_sha256(), secret_b.data(), static_cast<int>(secret_b.size()),
           hash_c.data(), hash_c.size(), verifier_d.data(),
           &hmac_len) == nullptr)
    throw std::runtime_error("HMAC computation failed");

  // ── Step 6: ED ← Enc(PKs, D) ───────────────────────────────────────────
  const std::vector<uint8_t> encrypted_d = EncryptWithServerPubKey(verifier_d);

  // ── Step 7: Store S locally; wipe all plaintext intermediates ──────────
  local_db[username] = salt_s;

  OPENSSL_cleanse(password.data(), password.size());
  OPENSSL_cleanse(secret_b.data(), secret_b.size());
  OPENSSL_cleanse(hash_c.data(), kHashSize);
  OPENSSL_cleanse(verifier_d.data(), kHashSize);

  // Return payload {U, E, ED, R} — server stores this as T_U.
  // Note: R is included so the server can use it during authentication;
  // it was never transmitted from server→user in plaintext as B⊕R,
  // only as the raw nonce before the user computed B⊕R.
  return {username, encrypted_b_xor_r, encrypted_d, server_r};
}

// Protocol 1 — Registration (3-arg convenience overload).
//
// Generates the server nonce R internally via CSPRNG and delegates to the
// 4-arg form. Intended for tests and single-process simulations where the
// caller does not need to observe or supply R.
auto RegisterUser(
    const std::string& username, std::vector<uint8_t>& password,
    std::unordered_map<std::string, std::vector<uint8_t>>& local_db)
    -> RegistrationPayload {
  const size_t kKeySize = 16;
  std::vector<uint8_t> server_r(kKeySize);
  if (RAND_bytes(server_r.data(), static_cast<int>(server_r.size())) != 1)
    throw std::runtime_error("CSPRNG failed generating server nonce R");
  return RegisterUser(username, password, server_r, local_db);
}

}  // namespace auth